services:
  db:
    image: postgres
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: password # Used in local environment and Pipelines

  app:
    build: .
    ports:
      - "8090:8080"
    env_file: "docker.env"
    environment:
      DBSTRING: postgresql://postgres:password@db/postgres?sslmode=disable
      
    
