services:
  db:
    image: postgres
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: password

  # app:
  #   build: .
  #   ports:
  #     - "8090:8080"
  #   environment:
  #     DBSTRING: postgresql://postgres:password@db/postgres?sslmode=disable
      
    
