name: testing
on:
  push:
    pull_request:
      - main


jobs:
  testing:

    runs_on: ubuntu-latest

     # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432


    steps:
      - uses: action/checkout@v2

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Run migrations
        run: make migrate/run
        env:
          DBSTRING: postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable

      - name: run test
        run: make ci/test


