name: testing
on:
  pull_request:
    branches: 
      - 'main'


jobs:
  testing:
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/creating-postgresql-service-containers
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          cache: true

      - name: setup templ
        run: |
          tag=$(curl -L -s -u "username:${{ github.token }}" https://api.github.com/repos/a-h/templ/releases/latest | jq -r '.tag_name')
          os="Linux"
          arch="x86_64"
          echo "Installing templ @ ${tag}  for ${os}_${arch}"
          curl -fsL https://github.com/a-h/templ/releases/download/${tag}/templ_${os}_${arch}.tar.gz > /tmp/templ.tar.gz
          tar -zxvf /tmp/templ.tar.gz
          mv templ /usr/local/bin/templ
          chmod +x /usr/local/bin/templ

      - name: build templates
        run: templ generate

      - name: create .env file
        run: cp .github/ci.env .env

      - name: setup goose
        uses: mscno/setup-goose@v1
      - name: Run migrations
        run: make migrate/run

      - name: run test
        run: make ci/test

